### ISSUE TITLE
lib files missing when downloaded from curse/twitch client

### ISSUE THREAD

**Issue by Numynum** [cr4ckp0t/ElvUI_ChatTweaks#1]
since the latest update (which removed some lib files from the git repo), the lib files have also disappeared when you download it from curse or the twitch client
causing some fatal errors, which means the addon stops functioning completely
adding the lib files back manually solves this, until the next time you update from twitch client

**Comment by jdm12983** [comment]
Manually download the latest file ( ElvUI_ChatTweaks-8.0.4.zip ) today ( May 27th 2019 ); and having this same issue. Have went back to version 8.0.3 for the time being.

**Comment by jdm12983** [comment]
Still an issue with 8.0.7 release. Kind of sucks to have a bug tracker if the author isn't reading and/or responding to it.

**Comment by Numynum** [comment]
I can see 1 lib got added back in, in the latest git version
still there's a bunch of libraries that are used by multiple modules, which aren't in git, and not in the packagemeta file

and merging the pull requests would be lovely as well, at least 1 of them is a complete no-brainer, don't even have to test it ingame

**Comment by cr4ckp0t** [comment]
When I download the file straight from Curse the libraries are present. The libraries that have their own project pages on Curse are packaged automatically by their packager and libraries are pulled in. That's why they're not on the GitHub repo.

There's no need to get snippy. I do this all for free and in my free time, which is considerably less given 8.2, my family, work, etc.

**Comment by cr4ckp0t** [comment]
Okay, Curse is now pulling everything correctly and the libraries are included. Closing this issue.

**Comment by Numynum** [comment]
I'm sorry if I came across overly rude, I was just excited to see this addon back in action (I've had a patched-up version since I installed wow in legion)
happy to see action again :)

regarding this issue, I'm still seeing multiple libs missing, both when downloading from twitch client and the curse website

- LibDataBroker-1.1
- LibDBIcon-1.0
- LibSink-2.0

I've never played around with the packager, so I can't make a pull request for it :/

**Comment by IrcDirk** [comment]
Sorry but again missing Libraries!

**Comment by cr4ckp0t** [comment]
Try: https://www.curseforge.com/wow/addons/elvui_chattweaks/files/2733803

It is beta to test the packager first before I do an actual release. As of this moment, it has not been approved by Curse so you may not be able to download it just yet.

**Comment by Numynum** [comment]
seems fine now; I'm not able to test it in-game, since I'm at the office; but I don't see why it wouldn't work :)
