### ISSUE TITLE
Multiple Lua errors (8.0.13) - also conflicts with Shadow and Light

### ISSUE THREAD

**Issue by MarkM793** [cr4ckp0t/ElvUI_ChatTweaks#10]
Hi,

Below LUA errors with build 8.0.13

`Message: ...ce\AddOns\ElvUI_ChatTweaks\Modules\PopupMessages.lua:5: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "LibSink-2.0".
Time: Thu Jul  4 17:46:17 2019
Count: 1
Stack: ...ce\AddOns\ElvUI_ChatTweaks\Modules\PopupMessages.lua:5: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "LibSink-2.0".
[C]: ?
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:189: in function `EmbedLibrary'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:171: in function `EmbedLibraries'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:250: in function `NewModule'
...ce\AddOns\ElvUI_ChatTweaks\Modules\PopupMessages.lua:5: in main chunk

Locals: `

`Message: ...rface\AddOns\ElvUI_ChatTweaks\Modules\SpamFilter.lua:69: attempt to index field 'CONFIRM_REPORT_SPAM_CHAT' (a nil value)
Time: Thu Jul  4 17:46:17 2019
Count: 1
Stack: ...rface\AddOns\ElvUI_ChatTweaks\Modules\SpamFilter.lua:69: attempt to index field 'CONFIRM_REPORT_SPAM_CHAT' (a nil value)
[C]: ?
...rface\AddOns\ElvUI_ChatTweaks\Modules\SpamFilter.lua:69: in main chunk

Locals: `

`Message: ...nterface\AddOns\ElvUI_ChatTweaks\Modules\SpamLog.lua:116: Usage: AceDBObject:GetNamespace(name): 'name' - namespace does not exist.
Time: Thu Jul  4 17:46:17 2019
Count: 1
Stack: ...nterface\AddOns\ElvUI_ChatTweaks\Modules\SpamLog.lua:116: Usage: AceDBObject:GetNamespace(name): 'name' - namespace does not exist.
(tail call): ?
[C]: ?
...erface\AddOns\DataStore\libs\AceDB-3.0\AceDB-3.0.lua:681: in function `GetNamespace'
...nterface\AddOns\ElvUI_ChatTweaks\Modules\SpamLog.lua:116: in function <...nterface\AddOns\ElvUI_ChatTweaks\Modules\SpamLog.lua:97>
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:498: in function `InitializeAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:613: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>

Locals: <none>`

`Message: (null)
Time: Thu Jul  4 17:46:26 2019
Count: 8`

`Message: Couldn't open Interface\AddOns\ElvUI_ChatTweaks\Libraries\Ace3\AceSerializer-3.0\AceSerializer-3.0.xml
Time: Thu Jul  4 17:46:26 2019
Count: 3`

`Message: Error loading Interface\AddOns\ElvUI_ChatTweaks\Libraries\LibDBIcon-1.0\LibDBIcon-1.0.lua
Time: Thu Jul  4 17:46:26 2019
Count: 3`

`Message: Couldn't open Interface\AddOns\ElvUI_ChatTweaks\Libraries\LibSink-2.0\lib.xml
Time: Thu Jul  4 17:46:26 2019
Count: 3`

`Message: ...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:160: attempt to call method 'Info' (a nil value)
Time: Thu Jul  4 17:46:28 2019
Count: 1
Stack: ...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:160: attempt to call method 'Info' (a nil value)
(tail call): ?
...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:160: in function <...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:137>
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\AddOns\ArkInventory\ArkInventory.lua:10143: in function `LoadAddOn'
Interface\AddOns\ArkInventory\ArkInventory.lua:10154: in function `BlizzardAPIHook'
Interface\AddOns\ArkInventory\ArkInventory.lua:2533: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2523>
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:450: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:569: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1210: in function <Interface\FrameXML\UIParent.lua:1108>

Locals: <none>`

**Comment by cr4ckp0t** [comment]
I'll take it look.

**Comment by cr4ckp0t** [comment]
Okay, I have just removed the entire Spam addon since there are better options out there and they're kept to update. Check out BadBoy by funkehdude. 8.0.15 should fix all of the library issues as well.

**Comment by MarkM793** [comment]
Thanks for the quick turnaround on this :)
