### ISSUE TITLE
Feature Request:  Create Chat links for Auto Grats

### ISSUE THREAD

**Issue by MarkM793** [cr4ckp0t/ElvUI_ChatTweaks#11]
Hi,
Thanks for this plug-in, only been using it a month, but its great.  One thing I would love to see is the congrats feature work like Prat.  It generates a link in chat when a person gets an achievement and I can configure a custom message to appear if I decide to click the link.  I know I can use your grats feature, and have been doing so, but turned it off recently as it was just spamming everything.  I know I can throttle it to a certain percentage, but what I used to do with Prat is just click the link for noteworthy achievements.  Our guild is almost 1000 people and lots of sometimes trivial achievements pop up which I do not want to "grats".  If this is doable, that would be awesome.  Thanks for your hard work (as a developer in a totally different industry, I appreciate the effort this has taken you)

**Comment by cr4ckp0t** [comment]
Just so I'm clear on what you're requesting: When someone gets an achievement it will print a link for you to click, if you chose, to congratulate them? Is that correct? If so, it should be doable I would think.

**Comment by MarkM793** [comment]
Yes that's it exactly.  So its "semi" automatic grats :)  The big thing for me is (like you do already) is to make it use the player name, as sometimes multiple achievements in a few seconds, so want to have that "grats Peter"  message appear when I click the link that "Peter" achieved

**Comment by Dervak** [comment]
Hello, thats simillar to a Prat functionallity, you can check it if you want to see what he's meaning!

**Comment by MarkM793** [comment]
> 
> 
> Hello, thats simillar to a Prat functionallity, you can check it if you want to see what he's meaning!

:)  Yes, I mentioned Prat in the initial request

**Comment by cr4ckp0t** [comment]
My apologies for the absurdly late response. Kind of took a bit of a break between 8.2 and 8.3. I have started writing the requested module. Should be done in a day or so.

**Comment by cr4ckp0t** [comment]
Added in version 8.0.21. Thanks again!

**Comment by MarkM793** [comment]
> Added in version 8.0.21. Thanks again!

Downloaded and already using it.  Thanks a lot :)
