### ISSUE TITLE
Elvui button not working

### ISSUE THREAD

**Issue by Dervak** [cr4ckp0t/ElvUI_ChatTweaks#13]
when i do activate the Extra Module, the Elvui game menu config button stop working and throw me this error:
2x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-73.lua:1892: AceConfigRegistry-3.0-20-ElvUI:ValidateOptionsTable(): ElvUI.args.EPDBC.type: expected a string, got a nil
[C]: ?
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:50: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:45>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:241: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:234>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:269: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:234>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:297: in function `ValidateOptionsTable'
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:339: in function `app'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-73.lua:1892: in function `?'
ElvUI\init.lua:377: in function <ElvUI\init.lua:296>
[C]: in function `ToggleOptionsUI'
ElvUI\init.lua:186: in function <ElvUI\init.lua:185>

Locals:
(*temporary) = "AceConfigRegistry-3.0-ElvUI:ValidateOptionsTable(): ElvUI.args.EPDBC.type: expected a string, got a nil"

only with the extra module, i did not tried any other module, if i deactivate that it works perfect

**Comment by cr4ckp0t** [comment]
Apologies for late response, it has been rather busy. I will take a look and get it fixed.

The Extra addon adds the following modules:
- Auto Set Role
- Calculator
- Color Rolls
- Companions
- Damage Meters
- Fake Achievement
- Fun Filters
- Gold Calculator
- Magic 8 Ball
- Pet Battles

Which ones are enabled for you? You can check in the ECT options. I use a few of them myself and haven't received any errors from the game menu button of EUI.

**Comment by yndrelbosch** [comment]
Still getting this error, and problem.

**Comment by cr4ckp0t** [comment]
Have not received a response. Closing.
