### ISSUE TITLE
ElvUI Chat Tweaks - Extra Modules Issue

### ISSUE THREAD

**Issue by acps87** [cr4ckp0t/ElvUI_ChatTweaks#17]
If i have the Extra Modules addon enabled I get the following error:

1x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:1863: AceConfigRegistry-3.0-20:ValidateOptionsTable(): ElvUI_ChatTweaks.args.Companions.args.hideButton: expected a table, got a boolean
[C]: ?
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:50: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:45>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:223: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:254: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:254: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:282: in function `ValidateOptionsTable'
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua:324: in function `app'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:1863: in function `?'
ElvUI_ChatTweaks\ElvUI_ChatTweaks-8.0.16.lua:347: in function `ToggleConfig'
...eElvUI_ChatTweaks\Modules\GamemenuButton.lua:31: in function <...eElvUI_ChatTweaks\Modules\GamemenuButton.lua:31>

Locals:
(*temporary) = "AceConfigRegistry-3.0:ValidateOptionsTable(): ElvUI_ChatTweaks.args.Companions.args.hideButton: expected a table, got a boolean"

Only solution right now is just to disable it, and then the base addon will work by itself.

**Comment by cr4ckp0t** [comment]
I am unable to reproduce your error.
