### ISSUE TITLE
Substitutions issue 

### ISSUE THREAD

**Issue by Fooforu** [cr4ckp0t/ElvUI_ChatTweaks#20]
15021x ...ceElvUI_ChatTweaks\Modules\Substitutions.lua:302: attempt to perform arithmetic on local 'x' (a nil value)
...ceElvUI_ChatTweaks\Modules\Substitutions.lua:302: in function `func'
...ceElvUI_ChatTweaks\Modules\Substitutions.lua:50: in function <...ceElvUI_ChatTweaks\Modules\Substitutions.lua:40>
(tail call): ?
(tail call): ?
(tail call): ?
(tail call): ?
(tail call): ?
(tail call): ?
(tail call): ?
(tail call): ?
(tail call): ?
Ace3\AceConsole-3.0\AceConsole-3.0-7.lua:47: in function <Ace3\AceConsole-3.0\AceConsole-3.0.lua:37>
...
ArkInventory\ArkInventory-30829.lua:10167: in function `BlizzardAPIHook'
ArkInventory\ArkInventory-30829.lua:2533: in function <ArkInventory\ArkInventory.lua:2523>
[C]: ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:450: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:569: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1210: in function <FrameXML\UIParent.lua:1108>

**Comment by cr4ckp0t** [comment]
Okay, I was able to figure out what was going on and fixed it in the latest version. Thanks for letting me know!
