### ISSUE TITLE
Feature Request:  DBM Separate Channel

### ISSUE THREAD

**Issue by EtherealRachus** [cr4ckp0t/ElvUI_ChatTweaks#22]
Hi.  Enjoying the project -- thanks. 
Request:  The ability to put DBM raid and instance messages in a separate chat window or channel.  I have found this:
https://www.deadlybossmods.com/forum/viewtopic.php?t=158

And the commands do work.  I think it would be a nice addition to your already incredibly extensive list of options.  Thanks again.

**Comment by cr4ckp0t** [comment]
You can do this yourself without needing any addon to do it by following the instructions in the link you provided. Don't really think it would warrant a module. But thanks for your kind words!
