### ISSUE TITLE
Channel Names! module

### ISSUE THREAD

**Issue by Fooforu** [cr4ckp0t/ElvUI_ChatTweaks#23]
Your Channel Names! module does not seem to be working even when Short Channel option is disabled in Elvui. no errors just flat does not work. also ElvUI Chat Tweaks[Extra Modules] and [Spam Modules] throw a bunch of errors and break ElvUI.

**Comment by cr4ckp0t** [comment]
When have you updated last? The Spam module has been removed for quite some time now.

**Comment by cr4ckp0t** [comment]
Channel Names works fine for me. If you can't provide errors, I can't really fix anything relating to the Extras module.
