### ISSUE TITLE
Request: Free Floating Edit Box

### ISSUE THREAD

**Issue by Fizgig1973** [cr4ckp0t/ElvUI_ChatTweaks#24]
Currently I am using Prat 3.0 + a few other small addons when I came across ChatTweaks. It's really amazing, and has so much to offer. I was hoping you could possible add the option to have a Free Floating Edit Box, and the ability to make frames smaller then default. These are the only 2 things that I am missing from Prat, and yours has so much more to offer.

Thank you for your time.

**Comment by cr4ckp0t** [comment]
Frame size can be adjusted with ElvUI the default UI. I can look into the Floating Edit Box, but can't promise anything.

**Comment by Fizgig1973** [comment]
Thank you very much.
