### ISSUE TITLE
Auto Congratulate and Auto Welcome Missing

### ISSUE THREAD

**Issue by Harrock** [cr4ckp0t/ElvUI_ChatTweaks#25]
After the last update I have a Semi-Auto Congratulate but any kind of welcome message is missing. Is this correct? If so, can we get a Semi-Auto Welcome message too?

**Comment by cr4ckp0t** [comment]
Hey, I may update to add semi-auto welcome, but it's not terribly high on my list. With how Blizzard changed sending chat messages, it's more annoying to automate it.
