### ISSUE TITLE
Elvui options not working when chat tweaks is installed

### ISSUE THREAD

**Issue by Jodsderechte** [cr4ckp0t/ElvUI_ChatTweaks#27]
for some reason whenever i install elvui_chat tweaks I'm unable to get into the elvui options. The button (once i hit escape) doesn't do anything and neither does /elvui once uninstalled both works like a charm again

**Comment by cr4ckp0t** [comment]
Make sure you're running the latest version. I am not having any issues getting to ElvUI's options frame.

**Comment by Jodsderechte** [comment]
reinstalled chat tweaks multiple times and made sure i had the current elvui version
using chat tweaks version 8.0.22 and elvui version 11.41

not sure if the bugsack info helps

7x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua:1952: AceConfigRegistry-3.0-20-ElvUI:ValidateOptionsTable(): ElvUI.args.EPDBC.type: expected a string, got a nil
[string "=[C]"]: ?
[string "@ElvUI_OptionsUI\Libraries\Ace3\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:50: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:45>
[string "@ElvUI_OptionsUI\Libraries\Ace3\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:241: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:234>
[string "@ElvUI_OptionsUI\Libraries\Ace3\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:269: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:234>
[string "@ElvUI_OptionsUI\Libraries\Ace3\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:297: in function `ValidateOptionsTable'
[string "@ElvUI_OptionsUI\Libraries\Ace3\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:339: in function `app'
[string "@ElvUI_OptionsUI\Libraries\Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1952: in function `?'
[string "@ElvUI\Core\Config.lua"]:1086: in function `ToggleOptionsUI'
[string "@ElvUI\init.lua"]:206: in function <ElvUI\init.lua:206>

Locals:
(*temporary) = "AceConfigRegistry-3.0-ElvUI:ValidateOptionsTable(): ElvUI.args.EPDBC.type: expected a string, got a nil"
