### ISSUE TITLE
Channel Name Tweak is not renaming [2. Trade - City]

### ISSUE THREAD

**Issue by Nythoria** [cr4ckp0t/ElvUI_ChatTweaks#28]
In the settings for Chat Tweaks I have all of them renamed to /X and for most is it working but for the actual Channels 1/2/3 is it not renaming them and leaving them as [1. General][2. Trade][3. Local Defense]

[https://i.imgur.com/lXVdmut.png](url)

**Comment by cr4ckp0t** [comment]
Make sure you're disabling ElvUI Short Channel option. ElvUI Options > Chat > General > Short Channels.

**Comment by Nythoria** [comment]
It is disabled

**Comment by Nythoria** [comment]
these are my settings with both windows open 
https://i.imgur.com/XF1NQkL.jpg

**Comment by Nythoria** [comment]
It is also now not renaming BNet Whispers from
https://i.imgur.com/GbfkDlx.png
