### ISSUE TITLE
Problems with the new Version

### ISSUE THREAD

**Issue by TaZzDE** [cr4ckp0t/ElvUI_ChatTweaks#33]
1x ...faceElvUI_ChatTweaks\Modules\PlayerNames.lua:549: attempt to call global 'GuildRoster' (a nil value)
[string "@ElvUI_ChatTweaks\Modules\PlayerNames.lua"]:549: in function <...faceElvUI_ChatTweaks\Modules\PlayerNames.lua:537>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:520>
[string "=(tail call)"]: ?
[string "@ElvUI_ChatTweaks\ElvUI_ChatTweaks-9.0.0.lua"]:191: in function <ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:138>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Ragwarod** [comment]
Message: ...face\AddOns\ElvUI_ChatTweaks\Modules\PlayerNames.lua:397: attempt to call upvalue 'GetNumFriends' (a nil value)
Time: Fri Oct 16 18:33:23 2020
Count: 2
Stack: ...face\AddOns\ElvUI_ChatTweaks\Modules\PlayerNames.lua:397: attempt to call upvalue 'GetNumFriends' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI_ChatTweaks\Modules\PlayerNames.lua"]:397: in function `?'
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by cr4ckp0t** [comment]
Fixed in 9.0.1.
