### ISSUE TITLE
ScrollReminder error

### ISSUE THREAD

**Issue by Pharou80** [cr4ckp0t/ElvUI_ChatTweaks#34]
ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
[string "@ElvUI\Core\Toolkit.lua"]:135: in function `SetTemplate'
[string "@ElvUI_ChatTweaks\Modules\ScrollReminder.lua"]:23: in function `CreateBottomButton'
[string "@ElvUI_ChatTweaks\Modules\ScrollReminder.lua"]:125: in function <...eElvUI_ChatTweaks\Modules\ScrollReminder.lua:121>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:520>
[string "=(tail call)"]: ?
[string "@ElvUI_ChatTweaks\ElvUI_ChatTweaks-9.0.1.lua"]:191: in function <ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:138>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
...
[string "=[C]"]: ?
[string "@ElvUI_SLE\core\toolkit.lua"]:307: in function `InitializeModules'
[string "@ElvUI_SLE\core\core.lua"]:85: in function `?'
[string "@ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0-36.lua"]:303: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI\init.lua"]:154: in function <ElvUI\init.lua:153>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by cr4ckp0t** [comment]
Thanks! Fixed in 9.0.2.
