### ISSUE TITLE
PlayerName lua error in 9.0.2

### ISSUE THREAD

**Issue by Thanatos0042** [cr4ckp0t/ElvUI_ChatTweaks#35]
Message: ...face\AddOns\ElvUI_ChatTweaks\Modules\PlayerNames.lua:574: attempt to call upvalue 'BNGetFriendInfo' (a nil value)
Time: Mon Oct 19 16:51:02 2020
Count: 1
Stack: ...face\AddOns\ElvUI_ChatTweaks\Modules\PlayerNames.lua:574: attempt to call upvalue 'BNGetFriendInfo' (a nil value)
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:520>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua"]:191: in function <...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:138>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\ElvUI_SLE\modules\professions\professions.lua"]:38: in function <...AddOns\ElvUI_SLE\modules\professions\professions.lua:35>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_SLE\core\toolkit.lua"]:307: in function `InitializeModules'
[string "@Interface\AddOns\ElvUI_SLE\core\core.lua"]:85: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua"]:303: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
[string "@Interface\AddOns\ElvUI\init.lua"]:156: in function <Interface\AddOns\ElvUI\init.lua:155>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by Thanatos0042** [comment]
also

Message: ...face\AddOns\ElvUI_ChatTweaks\Modules\PlayerNames.lua:549: attempt to call global 'GuildRoster' (a nil value)
Time: Wed Oct 21 21:52:02 2020
Count: 1
Stack: ...face\AddOns\ElvUI_ChatTweaks\Modules\PlayerNames.lua:549: attempt to call global 'GuildRoster' (a nil value)
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:520>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua"]:191: in function <...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:138>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by cr4ckp0t** [comment]
Disable the module for now. I have not had time to fix it and don't expect to be able to for some time.
