### ISSUE TITLE
Semi-Auto Congratulate

### ISSUE THREAD

**Issue by WeirDave** [cr4ckp0t/ElvUI_ChatTweaks#38]
I can never seem to get this to work. I am 100% sure it's user error but the links don't do anything.

Thanks for the assist in advance,

WeirDave

**Comment by Daveo7** [comment]
The link is no longer working for me. Not sure if the recent ElvUI update has changed something or not.

When I click link to congrats guildie, it used to do that, but last few days it's not done so. No errors displayed, just no congrats text in guild channel.

**Comment by cr4ckp0t** [comment]
If you don't tell me what it is or isn't doing, I can't help you.

**Comment by WeirDave** [comment]
I am in game and I get a notification in the chat window that someone has achieved something. I try to click on the link in my chat an it just makes a pop up that shows me the same message but does not seem to congratulate the person.
