### ISSUE TITLE
Achievement filter does not filter (Guild) achievements

### ISSUE THREAD

**Issue by Weissrolf** [cr4ckp0t/ElvUI_ChatTweaks#39]
Ahoi, just as the title says. v9.0.3 here. Being bombarded with guild achievements, which unfortunately are not filtered anymore.

**Comment by cr4ckp0t** [comment]
Is it checked to filter guild achievements? It does not do it by default.

**Comment by Weissrolf** [comment]
Yes, it is. No filtering happening.

**Comment by Weissrolf** [comment]
To disables achievement announcements I have to disables Blizzard's "Guild Announce" player messages, not "Achievement Announce". So maybe ChatTweaks filters the wrong channel/source?

**Comment by Weissrolf** [comment]
Any news on this? I still see both guild and close-by achievement announcements when both filters are enabled.

**Comment by cr4ckp0t** [comment]
No, the module works just fine. I tested it repeatedly using debugging to confirm it was filtering those messages. Are you using the enUS client?

**Comment by Weissrolf** [comment]
Ah, this could be it. I am using the German client.

**Comment by Weissrolf** [comment]
Would it be a lot of work to fix this for non enUS?
