### ISSUE TITLE
Lower part of Game Menu missing.

### ISSUE THREAD

**Issue by Fizgig1973** [cr4ckp0t/ElvUI_ChatTweaks#45]
Not sure why, but when I have Chat Tweaks loaded with just ElvUI the lower half of the Game Menu options are missing. Log Out, Exit Game, and Return to Game are just not there. Things cut off immediately after the ElvUI option, no space either. 

Verified this by disabling everything but ElvUI, ElvUI Options, and Chat Tweaks. 

Disabled everything at first, then loaded ElvUI, then ElvUI Options, and lastly Chat Tweaks. Reloading and checking after each addon was loaded. I've tested with numerous other addons as well, and the only time the Game Menu is affected is when Chat Tweaks is loaded as well. 

Some research shows that this could be an Ace 3 issue, as I was able to find similar instances of missing Game Menu functions related to ElvUI from past years, but nothing recently. 

I even uninstalled/reinstalled Ace3 from Curse, and then the newest version of Ace3 from 4 days ago and still no change.

**Comment by lbuchholz79** [comment]
Can confirm.

**Comment by cr4ckp0t** [comment]
Yeah, I am aware of this issue but just haven't gotten around to fixing it. As a work around turn on the Gamemenu Button module and reload your UI, it will temporarily fix the issue until I can figure out what's going on.

**Comment by cr4ckp0t** [comment]
I have removed the Gamemenu module in 9.0.7. I believe the issue is with the library that was used to create the button and I am unable to find an updated version.
