### ISSUE TITLE
Missing ACE3 Libraries

### ISSUE THREAD

**Issue by vderaa** [cr4ckp0t/ElvUI_ChatTweaks#46]
Unable to get this addon to load.  It complains of missing ACE3 Libraries.

3x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@ElvUI\Core\Libraries\Ace3\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@ElvUI_ChatTweaks\Libraries\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:7: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceGUI-3.0"."

3x ElvUI_ChatTweaks\ElvUI_ChatTweaks-9.0.6.lua:8: Cannot find a library instance of "AceConfigDialog-3.0".
[string "=[C]"]: in function `error'
[string "@ElvUI\Core\Libraries\Ace3\LibStub\LibStub.lua"]:23: in function `LibStub'
[string "@ElvUI_ChatTweaks\ElvUI_ChatTweaks-9.0.6.lua"]:8: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceConfigDialog-3.0"."

**Comment by cr4ckp0t** [comment]
Fixed in 9.0.7.
