### ISSUE TITLE
LUA error.

### ISSUE THREAD

**Issue by devilwalker** [cr4ckp0t/ElvUI_ChatTweaks#48]
Message: ...terface\AddOns\ElvUI_ChatTweaks\Modules\AltNames.lua:147: attempt to call global 'GuildRoster' (a nil value)
Time: Fri Mar 25 16:21:25 2022
Count: 1
Stack: ...terface\AddOns\ElvUI_ChatTweaks\Modules\AltNames.lua:147: attempt to call global 'GuildRoster' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI_ChatTweaks\Modules\AltNames.lua"]:147: in function `EnableGuildNotes'
[string "@Interface\AddOns\ElvUI_ChatTweaks\Modules\AltNames.lua"]:320: in function <...terface\AddOns\ElvUI_ChatTweaks\Modules\AltNames.lua:301>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:520>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua"]:191: in function <...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:138>
[string "=[C]"]: ?
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by dakhran** [comment]
There has been a simple one-line fix for a bug that has been in the game since 8.2.0, when GuildRoster() was moved to the C_GuildInfo namespace. Do we have maintainers anymore?

`147:		if IsInGuild() then C_GuildInfo.GuildRoster() end`
