### ISSUE TITLE
Not registered in AceConfigRegistry

### ISSUE THREAD

**Issue by raptormama** [cr4ckp0t/ElvUI_ChatTweaks#5]
Lua error:

```
Message: ...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:331: ElvUI_ChatTweaks isn't registed with AceConfigRegistry, unable to open config
Time: Sat Jun  1 19:55:15 2019
Count: 6
Stack: ...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:331: ElvUI_ChatTweaks isn't registed with AceConfigRegistry, unable to open config
(tail call): ?
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1798: in function `?'
...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:331: in function `ToggleConfig'
...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:116: in function <...terface\AddOns\ElvUI_ChatTweaks\ElvUI_ChatTweaks.lua:116>
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:50: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:48>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:818: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:639>
[C]: ?
Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:71: in function <Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:69>
Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:285: in function `Fire'
...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:22: in function <...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

Locals: <none>
```

**Comment by jdm12983** [comment]
Not much a point posting here it seems - this has been broken sense 8.0.4.

You should revert back to 8.0.3 for it to work properly again. However, I think with the ElvUI 11.12 Config change, you may not have proper access to the button to launch the config anyways. Haven't tested yet.

**Comment by jdm12983** [comment]
OK, tested version 8.0.3 - it works, but an error will pop up once each first time the menu is launched; saying an error about "toggleconfig". But, the menu still shows up and should work fine.

I know how to edit the LUA files so I changed it myself to point to the new ElvUI options menu.

**Comment by cr4ckp0t** [comment]
For some reason Curse has not been pulling my updates made on GitHub, and this is why nothing is being fixed. Also apparently GitHub does not notify of new issues...

**Comment by cr4ckp0t** [comment]
Okay, Curse is now pulling the GitHub updates correctly, and I have confirmed the libraries are included in the new packages. Sorry for the delay. I need to see how to turn on notifications for issues.
