### ISSUE TITLE
WowUp compatability

### ISSUE THREAD

**Issue by Starlynk1** [cr4ckp0t/ElvUI_ChatTweaks#51]
Since you use GitHub, can you make your addons WowUp compatible.

https://wowup.io/guide/wowup/hub

**Comment by WybeBosch** [comment]
Would love this very much aswell!!

**Comment by WybeBosch** [comment]
Am i doing something wrong? 
When i try and "install from URL" in wowup
using this url 
https://github.com/cr4ckp0t/ElvUI_ChatTweaks/releases/tag/9.1.2
![image](https://github.com/user-attachments/assets/f9baabf4-1c34-4966-adb4-49d1665c4d5b)
