### ISSUE TITLE
10.0.0 DragonFlight Pre-Patch

### ISSUE THREAD

**Issue by Daveo7** [cr4ckp0t/ElvUI_ChatTweaks#54]
Will this be updated for DragonFlight Pre-Patch (v10.0.0) ?

**Comment by dfurray** [comment]
Not sure, but you can get most of it to work by deleting anything including PopupMessages from the Modules.xml and I also deleted it from the modules folder. I haven't seen anything not working after that, but I haven't had much time to mess around either.
