### ISSUE TITLE
9.0.12 still throwing out the same issues.

### ISSUE THREAD

**Issue by dfurray** [cr4ckp0t/ElvUI_ChatTweaks#56]
9.0.12 isn't 10.0.0 compatible at all, not sure why it was posted as if it was.

**Comment by Daveo7** [comment]
Try fix as mentioned here >> https://github.com/cr4ckp0t/ElvUI_ChatTweaks/issues/53#issuecomment-1293479048

As this fix as got ChatTweaks working for me.

9.0.12 was just a TOC bump. It didn't include the above fix.

**Comment by dfurray** [comment]
I already had the fix done, I downloaded his update which undid the fix, see the problem?
