### ISSUE TITLE
MANY BUGS

### ISSUE THREAD

**Issue by kellow20** [cr4ckp0t/ElvUI_ChatTweaks#59]
There are many bugs with this update. My Elvui Windtools doesn't show, i get buggs out the butt on many things i dont understand, and im very good at reading a clearing bugs:D. It make many of my skins change for no reason.. I just installed it and those are what i've gotten. i've disabled all choices and only enabled a few, and still nothing changes. I really like this set up and want to keep it. Is it up to date with df? I have Elvui installed so that's notthe prob.. PLease help. THANKS! 

This is what im getting right after log on. 

6x ElvUI_ChatTweaks/ElvUI_ChatTweaks.lua:131: attempt to call method 'ToggleOptionsUI' (a nil value)
[string "@ElvUI_ChatTweaks/ElvUI_ChatTweaks.lua"]:131: in function <ElvUI_ChatTweaks/ElvUI_ChatTweaks.lua:131>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@ElvUI_Libraries/Core/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:869: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:691>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <.../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-Button-ElvUI.lua"]:85: in function <...ce3/AceGUI-3.0/widgets/AceGUIWidget-Button-ElvUI.lua:82>
[string "=[C]"]: ?

**Comment by cr4ckp0t** [comment]
This is already being tracked in #58.
