### ISSUE TITLE
addon keeps disabling itself

### ISSUE THREAD

**Issue by G1ak1** [cr4ckp0t/ElvUI_ChatTweaks#60]
Hello. 

Since the launch of 10.0.7 the addon keeps disabling itself. i go to my addons manually enable it again, reload ui and no change, it changes back to disable. i checked with only elvui and elvui chat tweaks enabled and the same thing happens.

any idea what might be wrong???  really missing my chat flashing on new messages :P

thanks in advance

**Comment by G1ak1** [comment]
ok as i found out this addon was blacklisted by elvui??? and elvui is the one disabling this. any solution???

cant live without the hat flash option :P

**Comment by Daveo7** [comment]
Fixed the disabling of ElvUI Chat Tweaks, see here > https://github.com/cr4ckp0t/ElvUI_ChatTweaks/issues/58#issuecomment-1484099433

ElvUI is disabling ElvUI Chat Tweaks during init of ElvUI. Not sure they are allowed to do this ?

**Comment by Araldwenn** [comment]
Guess they do this because Elvui ChatTweak is actually not functionning for a long time without making adjustment most people are unable to do, and was messing things up.
