### ISSUE TITLE
Multiple issues in subsitutions

### ISSUE THREAD

**Issue by Numynum** [cr4ckp0t/ElvUI_ChatTweaks#7]
there's a few bugs in Subsitutions module, most of them are fixed in https://github.com/cr4ckp0t/ElvUI_ChatTweaks/pull/6
there's 1 final issue though, for which I'm not going to throw in a PR without any conversation

Blizzard has build in substitutions already, which include "%t", because of this, anything which starts with these strings, will be substituted with either the target name, or "<no target>"
the Substitutions module uses %xxx% as replacement pattern, which means NONE of the target substitutions will work (eg. "%tn%" would result in "*targetname*n%")

there's 3 options:
1. either the target patterns need a new starting letter
2. all patterns use a different special character instead (eg. "$tn$ for target name")
3. remove target patterns from the list, cause they don't work, an things that don't work shouldn't say they do

I personally prefer option 2, which is what I'm using locally now

**Comment by cr4ckp0t** [comment]
I like option 2 as well. I'll put it in.

**Comment by cr4ckp0t** [comment]
I have added this and it will be in 8.0.13.
