### ISSUE TITLE
Doesnt work since months for me.

### ISSUE THREAD

**Issue by Solence1** [cr4ckp0t/ElvUI_ChatTweaks#9]
I have the addon since a  decent long time already and it doesn't work at all.I kept it for months for the offchance that an update will make it work but it never happens anything. The update rolls in but nether the commands open any settings nor the menu over elvui settings. What do i have to do to get the addon even do anything? I mean it is supposed to work right?

**Comment by cr4ckp0t** [comment]
And how exactly do you expect me to help you if you provide _ZERO_ error messages?

**Comment by Solence1** [comment]
well the addon not working doesn't automatically mean it throws out errors. It just didn't load. But your update today fixed it.
